# Generated by Django 4.1.10 on 2023-08-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
