# Generated by Django 4.1.10 on 2023-08-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
