# Generated by Django 4.1.10 on 2023-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_last_login_account_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
