# Generated by Django 4.1.13 on 2023-12-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='social1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='social2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
