# Generated by Django 4.1.13 on 2023-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_social1_account_social2'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vocals',
            field=models.BooleanField(default=False),
        ),
    ]
