# Generated by Django 4.1.13 on 2023-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_instrument_account_mixmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='social1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='social2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
