# Generated by Django 4.0.7 on 2023-07-24 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkietaOtw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytol', models.CharField(max_length=40)),
                ('pytanie', models.CharField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('kategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OdpowiedzOtw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=700)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ankietaotw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankiety.ankietaotw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
