# Generated by Django 4.2.7 on 2024-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0002_rename_data_ankietaotw_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankietaotw',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
