# Generated by Django 4.2.7 on 2024-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0003_alter_ankietaotw_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankietaotw',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
