# Generated by Django 4.2.7 on 2024-05-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0004_alter_ankietaotw_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odpowiedzotw',
            old_name='poll',
            new_name='ankietaotw',
        ),
    ]
