# Generated by Django 4.2.7 on 2024-06-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideas',
            old_name='instrument',
            new_name='acoustic',
        ),
        migrations.AddField(
            model_name='ideas',
            name='beat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideas',
            name='drums',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideas',
            name='electronic',
            field=models.BooleanField(default=False),
        ),
    ]
