# Generated by Django 4.2.7 on 2024-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_instrument_ideas_acoustic_ideas_beat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='acoustic',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='beat',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='drums',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='electronic',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='rap',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='vocals',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
