# Generated by Django 4.1.10 on 2023-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='download_pack',
            field=models.FileField(null=True, upload_to='collabs/downloads'),
        ),
        migrations.AddField(
            model_name='collabsub',
            name='file',
            field=models.FileField(null=True, upload_to='collabs/downloads'),
        ),
    ]
