# Generated by Django 4.1.10 on 2023-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0003_collabsub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='download_pack',
            field=models.FileField(blank=True, null=True, upload_to='collabs/downloads'),
        ),
    ]
