# Generated by Django 4.1.10 on 2023-08-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0004_alter_collab_download_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabsub',
            name='odpowiedz',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='collabsub',
            name='sprawdzone',
            field=models.BooleanField(default=False),
        ),
    ]
