# Generated by Django 4.1.10 on 2023-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0005_collabsub_odpowiedz_collabsub_sprawdzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='glosowanie',
            field=models.BooleanField(default=False),
        ),
    ]
