# Generated by Django 4.1.10 on 2023-08-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0007_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='collab_name',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.collabsub')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.voting')),
            ],
        ),
    ]
