# Generated by Django 4.1.13 on 2023-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0008_voting_collab_name_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='collab_name',
        ),
        migrations.AddField(
            model_name='voting',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='voting',
            name='voting_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
