# Generated by Django 4.1.13 on 2023-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0009_remove_voting_collab_name_voting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
