# Generated by Django 4.1.13 on 2023-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0010_alter_vote_voter_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
