# Generated by Django 4.1.13 on 2023-12-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0012_voting_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='voting_name',
            new_name='name',
        ),
    ]
