# Generated by Django 4.1.13 on 2023-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0013_rename_voting_name_voting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
