# Generated by Django 4.1.13 on 2023-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0014_voting_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='instrument',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='rap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='wokal',
            field=models.BooleanField(default=False),
        ),
    ]
