# Generated by Django 4.2.7 on 2024-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0015_collab_instrument_collab_rap_collab_wokal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='ableton',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='backing_track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='desc2',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='collab',
            name='desc2_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='collab',
            name='desc_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='collab',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collab',
            name='logic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='midi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='reaper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collab',
            name='title_en',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collab',
            name='desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
