# Generated by Django 4.2.7 on 2024-05-15 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collabs', '0016_collab_ableton_collab_backing_track_collab_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackDownloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.collab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='packdownloads',
            constraint=models.UniqueConstraint(models.F('user'), models.F('collab'), name='pack-download'),
        ),
    ]
