# Generated by Django 4.2.7 on 2024-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0017_packdownloads_packdownloads_pack_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='description_en',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='voting',
            name='name_en',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
