# Generated by Django 4.2.7 on 2024-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0021_rename_glosowanie_collab_votingactive_collab_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabsub',
            name='volumeOffset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
