# Generated by Django 4.2.7 on 2024-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0022_collabsub_volumeoffset'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabsub',
            name='demo_file_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
