# Generated by Django 4.2.7 on 2024-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0023_collabsub_demo_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name_en',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
