# Generated by Django 4.2.7 on 2024-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0024_alter_voting_name_alter_voting_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
