# Generated by Django 4.2.7 on 2024-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0026_stages_remove_collab_ableton_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='stages',
            name='desc_pl',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stages',
            name='name_pl',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddConstraint(
            model_name='packdownloads',
            constraint=models.UniqueConstraint(models.F('user'), models.F('stage'), name='pack-download'),
        ),
    ]
