# Generated by Django 4.2.7 on 2024-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0027_remove_packdownloads_pack_download_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='stages',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
