# Generated by Django 4.2.7 on 2024-07-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0028_remove_packdownloads_pack_download_alter_stages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='open',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collabsub',
            name='msg',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
