# Generated by Django 4.2.7 on 2024-07-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0029_remove_packdownloads_pack_download_stages_open_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='stages',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collabs.collabsub'),
        ),
    ]
