# Generated by Django 4.2.7 on 2024-07-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0033_remove_packdownloads_pack_download'),
    ]

