# Generated by Django 4.2.7 on 2024-07-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupmembership_joined'),
        ('collabs', '0034_remove_packdownloads_pack_download'),
    ]

    operations = [

        migrations.AddField(
            model_name='collab',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
    ]
