# Generated by Django 4.2.7 on 2024-07-21 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collabs', '0035_remove_packdownloads_pack_download_collab_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        # migrations.RemoveConstraint(
        #     model_name='packdownloads',
        #     name='pack-download',
        # ),
        migrations.AddField(
            model_name='listened',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.stages'),
        ),
        migrations.AddField(
            model_name='listened',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.collabsub'),
        ),
        migrations.AddField(
            model_name='listened',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favouriteresponse',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.collabsub'),
        ),
        migrations.AddField(
            model_name='favouriteresponse',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collabs.stages'),
        ),
        migrations.AddField(
            model_name='favouriteresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favouriteresponse',
            unique_together={('user', 'selection', 'stage')},
        ),
    ]
