# Generated by Django 4.2.7 on 2024-07-21 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collabs', '0036_favouriteresponse_listened_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteResponse',
            new_name='Favourite',
        ),
        # migrations.RemoveConstraint(
        #     model_name='packdownloads',
        #     name='pack-download',
        # ),
    ]
