# Generated by Django 4.2.7 on 2024-08-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabs', '0037_rename_favouriteresponse_favourite_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='favourite',
            name='final',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
