# Generated by Django 4.2.7 on 2024-07-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mods',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='group',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='Mods',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
