# Generated by Django 4.2.7 on 2024-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_mods_group_remove_mods_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='desc',
            field=models.TextField(default='test', max_length=420),
            preserve_default=False,
        ),
    ]
