# Generated by Django 4.2.7 on 2024-07-17 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
