# Generated by Django 4.1.13 on 2024-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampel',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
