# Generated by Django 4.1.10 on 2023-07-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_remove_sampel_points_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampel',
            name='owner',
        ),
    ]
