# Generated by Django 4.1.10 on 2023-07-30 11:08

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_downloads'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downloads',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='downloads',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('user'), models.OrderBy(django.db.models.functions.text.Lower('sample'), descending=True), name='download'),
        ),
    ]
