# Generated by Django 4.1.10 on 2023-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_alter_downloads_unique_together_downloads_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampel',
            old_name='mp3_file',
            new_name='demo',
        ),
        migrations.AddField(
            model_name='sampel',
            name='file',
            field=models.FileField(null=True, upload_to='music/'),
        ),
    ]
