# Generated by Django 4.1.10 on 2023-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_rename_mp3_file_sampel_demo_sampel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
